quarkus.http.port=8080

demo.ui.amq1-label=AMQ1
demo.ui.amq1-color=#2563eb
demo.ui.amq2-label=AMQ2
demo.ui.amq2-color=#16a34a
demo.ui.amq3-label=AMQ3
demo.ui.amq3-color=#a21caf

demo.consumers.amq1-snapshot-url=
demo.consumers.amq2-snapshot-url=
demo.consumers.amq3-snapshot-url=

demo.jolokia.amq1-base-url=
demo.jolokia.amq2-base-url=
demo.jolokia.amq3-base-url=
demo.jolokia.username=admin
demo.jolokia.password=admin

