quarkus.http.port=8080

demo.ui.amq1-label=AMQ1
demo.ui.amq1-color=#2563eb
demo.ui.amq2-label=AMQ2
demo.ui.amq2-color=#16a34a
demo.ui.amq3-label=AMQ3
demo.ui.amq3-color=#a21caf

demo.jolokia.username=admin
demo.jolokia.password=admin

demo.ha.site=amq1
demo.ha.namespace=amq-multicluster-amq
demo.ha.broker-cr=AUTO
demo.ha.username=admin
demo.ha.password=admin
demo.ha.queue=iot.events.v3
demo.ha.queue-routing-type=multicast
demo.ha.topic=iot.events.v3

