apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  name: amq-amq3-mirror
  namespace: amq-multicluster
  annotations:
    argocd.argoproj.io/sync-wave: "22"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  routingKey: amq-amq3-mirror
  selector: ActiveMQArtemis=amq-amq3
  port: 5672

