quarkus.http.port=8081

demo.broker.url=${DEMO_BROKER_URL:(tcp://localhost:61616)?ha=true&reconnectAttempts=-1&retryInterval=1000&retryIntervalMultiplier=1.0}
demo.broker.username=${DEMO_BROKER_USERNAME:admin}
demo.broker.password=${DEMO_BROKER_PASSWORD:admin}
demo.broker.queue=${DEMO_BROKER_QUEUE:iot.events.v3}
demo.broker.site=${DEMO_BROKER_SITE:amq1}

demo.mqtt.host=${DEMO_MQTT_HOST:}
demo.mqtt.port=${DEMO_MQTT_PORT:8883}
demo.mqtt.topic=${DEMO_MQTT_TOPIC:iot.events.v3}
demo.mqtt.insecure-tls=${DEMO_MQTT_INSECURE_TLS:true}
demo.mqtt.site=${DEMO_MQTT_SITE:amq1}

