apiVersion: skupper.io/v2alpha1
kind: AccessGrant
metadata:
  name: grant-amq1
  namespace: amq-multicluster-skupper
  annotations:
    argocd.argoproj.io/sync-wave: "21"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  redemptionsAllowed: 2
  expirationWindow: 1h

