apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: amq-amq1
  namespace: amq-multicluster-amq
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  deploymentPlan:
    size: 2
    clustered: true
    persistenceEnabled: true
    requireLogin: false
    messageMigration: true
    storage:
      size: 10Gi
  adminUser: admin
  adminPassword: admin
  console:
    expose: true
  acceptors:
    - name: mqtts
      protocols: mqtt
      port: 8883
      sslEnabled: true
      sslSecret: amq-tls-mqtt
      expose: true
      verifyHost: false
    - name: amqp
      protocols: amqp
      port: 5672
      sslEnabled: false
      expose: false
  brokerProperties:
    - "addressSettings.#.autoCreateAddresses=true"
    - "addressSettings.#.autoCreateQueues=true"
    - "addressSettings.#.autoCreateJmsQueues=true"
    - "addressSettings.#.autoCreateJmsTopics=true"
    - "AMQPConnections.toAmq2.uri=tcp://amq-amq2-mirror.amq-multicluster-skupper.svc:5672"
    - "AMQPConnections.toAmq2.user=admin"
    - "AMQPConnections.toAmq2.password=admin"
    - "AMQPConnections.toAmq2.retryInterval=5000"
    - "AMQPConnections.toAmq2.connectionElements.mirror.type=MIRROR"
    - "AMQPConnections.toAmq2.connectionElements.mirror.messageAcknowledgements=true"
    - "AMQPConnections.toAmq2.connectionElements.mirror.queueCreation=true"
    - "AMQPConnections.toAmq2.connectionElements.mirror.queueRemoval=true"
    - "AMQPConnections.toAmq3.uri=tcp://amq-amq3-mirror.amq-multicluster-skupper.svc:5672"
    - "AMQPConnections.toAmq3.user=admin"
    - "AMQPConnections.toAmq3.password=admin"
    - "AMQPConnections.toAmq3.retryInterval=5000"
    - "AMQPConnections.toAmq3.connectionElements.mirror.type=MIRROR"
    - "AMQPConnections.toAmq3.connectionElements.mirror.messageAcknowledgements=true"
    - "AMQPConnections.toAmq3.connectionElements.mirror.queueCreation=true"
    - "AMQPConnections.toAmq3.connectionElements.mirror.queueRemoval=true"

