apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: device-simulator
  namespace: amq-multicluster-apps
  annotations:
    argocd.argoproj.io/sync-wave: "40"
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: event-consumer
  namespace: amq-multicluster-apps
  annotations:
    argocd.argoproj.io/sync-wave: "40"
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: visualizer
  namespace: amq-multicluster-apps
  annotations:
    argocd.argoproj.io/sync-wave: "40"

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: queue-producer
  namespace: amq-multicluster-apps
  annotations:
    argocd.argoproj.io/sync-wave: "40"

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: camel-kaoto-consumer
  namespace: amq-multicluster-apps
  annotations:
    argocd.argoproj.io/sync-wave: "40"

