apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespace
  - namespace.yaml

  # Operators
  - amq-broker-operatorgroup.yaml
  - amq-broker-subscription.yaml
  - rhsi-subscription.yaml

  # AMQ runtime
  - amq-tls-mqtt-secret.yaml
  - addresses-queues.yaml
  - broker.yaml

  # Service Interconnect (RHSI/Skupper v2)
  - site.yaml
  - amq-connectors.yaml
  - amq-listeners.yaml
  - access-grant.yaml

  # Apps (build + run)
  - imagestreams.yaml
  - buildconfigs.yaml
  - apps.yaml

