apiVersion: skupper.io/v2alpha1
kind: Site
metadata:
  name: amq1
  namespace: amq-multicluster
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  linkAccess: default

