apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-amq.yaml
  - namespace-skupper.yaml
  - namespace-apps.yaml

  - amq-broker-operatorgroup.yaml
  - amq-broker-subscription.yaml
  - rhsi-subscription.yaml
  - rhsi-netobs-subscription.yaml

  - amq-tls-mqtt-secret.yaml
  - addresses-queues.yaml
  - broker.yaml
  - mqtts-lb-service.yaml

  - site.yaml
  - network-observer.yaml
  - amq-connectors.yaml
  - mqtt-connectors.yaml
  - amq-listeners.yaml
  - access-grant.yaml

  # Filled by automation after AccessGrant is ready on amq1:
  # - access-token-to-amq1.yaml

  - imagestreams.yaml
  - buildconfigs.yaml
  - apps.yaml

  - console-banner.yaml
  - console-links.yaml

