apiVersion: skupper.io/v2alpha1
kind: Site
metadata:
  name: amq2
  namespace: amq-multicluster-skupper
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

spec:
  linkAccess: default

