demo.mqtt.host=localhost
demo.mqtt.port=8883
demo.mqtt.tls=true
demo.mqtt.username=admin
demo.mqtt.password=admin
demo.mqtt.site=amq1
demo.mqtt.device-count=10
demo.mqtt.interval-ms=250
# For "no duplicates" demos prefer qos=0
demo.mqtt.qos=0

# When tls=true you must provide a truststore
demo.mqtt.trust-store-path=
demo.mqtt.trust-store-password=

# Optional mTLS
demo.mqtt.key-store-path=
demo.mqtt.key-store-password=

