all:
  vars:
    git_repo_url: "https://github.com/panchoraposo/amq-multicluster.git"
  hosts:
    amq1:
      oc_context: "amq1"
    amq2:
      oc_context: "amq2"
    amq3:
      oc_context: "amq3"

