# Camel YAML routes (Kaoto-friendly)
camel.main.routes-include-pattern=routes/*.yaml

# Postgres datasource (service: postgres)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/sensordb
quarkus.datasource.username=sensor
quarkus.datasource.password=sensor

# MQTT input (defaults target AMQ1 internal mqtt-lb)
demo.mqtt.host=amq-amq1-mqtt-lb.amq-multicluster-amq.svc
demo.mqtt.port=1883
demo.mqtt.username=admin
demo.mqtt.password=admin
demo.mqtt.topic=sensors/#
demo.mqtt.insecure-tls=true

